### ISSUE TITLE
Transactions table migration issue

### ISSUE THREAD

**Issue by ImAliSheraz** [devinweb/laravel-hyperpay-boilerplate#5]
I'm trying to set up this project. But, Whenever I try to migrate it shows a foreign key error in the transaction table. I also attached a screenshot. I can't able find this migration file in the code.
![Screenshot 2022-07-25 181404](https://user-images.githubusercontent.com/56052998/180785833-6a4a2e13-ebc4-4ccc-b781-f4a3555154b2.png)

**Comment by darbaoui** [comment]
I think the issue was fixed LMK if that issue still exists

**Comment by ImAliSheraz** [comment]
No that's not resolved.

**Comment by darbaoui** [comment]
@ImAliSheraz Fix https://github.com/devinweb/laravel-hyperpay-boilerplate/commit/92bc8bef64d1915a692de85df1163cd58d9ecd84

**Comment by darbaoui** [comment]
@ImAliSheraz could you please close the issue

**Comment by ImAliSheraz** [comment]
Sure
